version: "3.7"

services:
  dl-loading-ui:
    image: camdl/dl-loading-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOADING_UI_HARDCODED_USERS_FILE: ${LOADING_UI_HARDCODED_USERS_FILE}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${LOADING_UI_PORT_EXT}:${LOADING_UI_PORT_INT}
    volumes:
       - ./docker/dl-data-samples/source-data:/mnt/s3data
    depends_on:
      - dl-loading-db

  dl-loading-db:
    build:
      context: docker/dl-loading-db
      dockerfile: Dockerfile
      args:
        LOADING_DB_USER_SETUP_SQL: ${LOADING_DB_USER_SETUP_SQL}
        POSTGRES_PASSWORD: ${LOADING_DB_PASSWORD}
    restart: always
    image: camdl/dl-loading-db:latest
    volumes:
      - dl-loading-db:/var/lib/postgresql/data
    command: -p ${LOADING_DB_PORT_INT}
    environment:
      POSTGRES_USER: ${LOADING_DB_USER}
      POSTGRES_DB: ${LOADING_DB_DATABASE}
      POSTGRES_PASSWORD: ${LOADING_DB_PASSWORD}

volumes:
  dl-loading-db:
